Implement service configuration option for WebDAV maximum upload file with NextCloud 27.x
Start9Labs/nextcloud-startos pull request #52
Opened 2023-11-09 18:10 UTC by dfkc6

This is the continuation of #51. Checked it again and the same thing happens with nginx, it also has the same default 1G of maximum upload size limitation through webdav. 

Just to reiterate this happens when mounting a webdav directory through the command line and trying to copy a file over which is bigger than the limit. With this fix, there will be a new config option before starting the service for setting this upload limit size. Special option is setting it to 0 because that removes any upload size limitation, theoretically any file with any size could be uploaded, if it fits into the quota size of the NextCloud share into it is being uploaded.

Might be just an edge case but it still could be useful to be able to configure this.

2023-11-27 16:42 UTC, dr-bonez requested changes

2023-11-27 16:42 UTC, dr-bonez commented on scripts/services/getConfig.ts
> +        "range": "[0,2048]",
```suggestion
        "units": "MiB",
        "nullable": true,
        "integral": true,
        "range": "(0,2048]",
```

2023-11-27 16:42 UTC, dr-bonez commented on docker_entrypoint.sh
> +sed -i "s/client_max_body_size\ 1024M/client_max_body_size\ $WEBDAV_MAX_UPLOAD_FILE_SIZE_LIMIT$([[ "$WEBDAV_MAX_UPLOAD_FILE_SIZE_LIMIT" == "0" ]] && echo "" || echo "M")/g" /etc/nginx/http.d/default.
```suggestion
sed -i "s/client_max_body_size\ 1024M/client_max_body_size\ $([[ "$WEBDAV_MAX_UPLOAD_FILE_SIZE_LIMIT" == "null" ]] && echo "0" || echo "${WEBDAV_MAX_UPLOAD_FILE_SIZE_LIMIT}M")/g" /etc/nginx/http.d/default.conf
```

2024-01-17 19:39 UTC, kn0wmad commented
@dfkc6 Apologies for the slow movement here.  We finally released v26, which was pre-requisite as Nextcloud does not support jumping major versions.  This was also a major refactor which will much improve future versions, updates, and migrations.  Would you mind rebasing this to the `update/v27.1.5` branch?  I will get it merged in right away, and we'll be moving to release v27 fairly quickly.  Just want to address a couple minor bugs and add some features (such as this one).  Thank you for your patience.

2024-01-31 15:14 UTC, kn0wmad commented
Code added to #61 instead

2024-01-31 15:14 UTC, closed without merging